### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by lextor88** [ToadKing/apple-music-barcode-isrc#2]
Since yesterday I get the error message: "SyntaxError: JSON Parse error: Unexpected EOF"

Tested with Safari (Userscripts), Chrome and Firefox (Violentmonkey , tampermonkey)

**Comment by ToadKing** [comment]
Fixed in 0.18, had to update the server token

**Comment by lextor88** [comment]
It works!!! Many thanks.
